services:
  - type: web
    name: parkinsons-api
    runtime: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install --only-binary=:all: -r requirements.txt"
    startCommand: "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 8000
